#!/bin/bash
# =============================================================
# deploy-sevis-web.sh — Build Angular frontend & deploy to EC2
# Usage: bash scripts/deploy-sevis-web.sh
# =============================================================

set -euo pipefail
source "$(dirname "$0")/config.sh"

WEB_SOURCE="$PROJECT_ROOT/sevis-web"
REMOTE_WEB_DIR="$APP_DIR/sevis-web"
WEB_PORT=80

BOLD='\033[1m'; GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; RESET='\033[0m'

log()   { echo -e "${CYAN}>>> $*${RESET}"; }
ok()    { echo -e "${GREEN}  ✓ $*${RESET}"; }
fail()  { echo -e "${RED}  ✗ $*${RESET}"; }
warn()  { echo -e "${YELLOW}  ⚠ $*${RESET}"; }
header(){ echo -e "\n${BOLD}$*${RESET}"; }

# ══════════════════════════════════════════════════════════════
# 1. Pre-flight: check all server services
# ══════════════════════════════════════════════════════════════
header "════════════════════════════════════════"
header " Pre-flight: Sevis Server Status"
header "════════════════════════════════════════"

$SSH_CMD bash << 'CHECKSH'
BOLD='\033[1m'; GREEN='\033[0;32m'; RED='\033[0;31m'; RESET='\033[0m'
BASE=~/sevis

echo ""
echo -e "${BOLD}Java Microservices:${RESET}"
for SVC in eureka-server gateway user-service billing-service inventory-service orders-service; do
  PID_FILE=$BASE/$SVC.pid
  if [ -f "$PID_FILE" ]; then
    PID=$(cat "$PID_FILE")
    if kill -0 "$PID" 2>/dev/null; then
      echo -e "  ${GREEN}✓${RESET} $SVC  (PID $PID)"
    else
      echo -e "  ${RED}✗${RESET} $SVC  (PID $PID — stale, not running!)"
    fi
  else
    echo -e "  ${RED}✗${RESET} $SVC  (no PID file)"
  fi
done

echo ""
echo -e "${BOLD}Listening ports:${RESET}"
sudo ss -tlnp 2>/dev/null | awk 'NR>1{print "  " $4}' | sort -t: -k2 -n

echo ""
echo -e "${BOLD}Memory:${RESET}"
free -h | grep Mem | awk '{printf "  Total: %s  Used: %s  Free: %s  Available: %s\n", $2,$3,$4,$7}'
CHECKSH

# ══════════════════════════════════════════════════════════════
# 2. Build Angular (production)
# ══════════════════════════════════════════════════════════════
header "════════════════════════════════════════"
header " Building Angular (production)"
header "════════════════════════════════════════"

if [ ! -d "$WEB_SOURCE" ]; then
  echo -e "${RED}ERROR: sevis-web directory not found at $WEB_SOURCE${RESET}"
  exit 1
fi

cd "$WEB_SOURCE"
log "Running: ng build --configuration production"
npm run build -- --configuration production
ok "Build complete"

DIST_DIR="$WEB_SOURCE/dist/sevis-web/browser"
if [ ! -d "$DIST_DIR" ]; then
  echo -e "${RED}ERROR: dist not found at $DIST_DIR${RESET}"
  exit 1
fi

DIST_SIZE=$(du -sh "$DIST_DIR" | cut -f1)
log "Dist size: $DIST_SIZE"

# ══════════════════════════════════════════════════════════════
# 3. Upload dist to EC2
# ══════════════════════════════════════════════════════════════
header "════════════════════════════════════════"
header " Uploading to EC2"
header "════════════════════════════════════════"

log "Creating remote directory: $REMOTE_WEB_DIR"
$SSH_CMD "mkdir -p $REMOTE_WEB_DIR"

log "Packaging dist..."
TARBALL="/tmp/sevis-web-$(date +%s).tar.gz"
tar czf "$TARBALL" -C "$DIST_DIR" .
log "Uploading $(du -sh "$TARBALL" | cut -f1) tarball..."
scp -i "$EC2_KEY" -o StrictHostKeyChecking=no "$TARBALL" "$EC2_USER@$EC2_HOST:/tmp/sevis-web.tar.gz"
rm -f "$TARBALL"

log "Extracting on server..."
$SSH_CMD "tar xzf /tmp/sevis-web.tar.gz -C $REMOTE_WEB_DIR && rm /tmp/sevis-web.tar.gz"

log "Setting permissions for nginx..."
$SSH_CMD "chmod o+x /home/ec2-user /home/ec2-user/sevis && chmod -R o+rX $REMOTE_WEB_DIR"
ok "Upload complete"

# ══════════════════════════════════════════════════════════════
# 4. Write nginx config locally, upload, activate
# ══════════════════════════════════════════════════════════════
header "════════════════════════════════════════"
header " Configuring nginx"
header "════════════════════════════════════════"

NGINX_CONF_LOCAL="/tmp/sevis-web-nginx.conf"
cat > "$NGINX_CONF_LOCAL" << EOF
# Sevis CRM — Angular SPA
# Generated by deploy-sevis-web.sh on $(date)

server {
    listen ${WEB_PORT} default_server;
    server_name _;

    root ${REMOTE_WEB_DIR};
    index index.html;

    # ── SPA fallback ──────────────────────────────────────────
    # All routes handled by Angular Router; unknown paths fall back to index.html
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # ── index.html — never cache (app entry point) ────────────
    location = /index.html {
        add_header Cache-Control "no-store, no-cache, must-revalidate";
        add_header Pragma "no-cache";
    }

    # ── Hashed JS/CSS bundles — cache forever ─────────────────
    # Angular production builds emit content-hashed filenames
    location ~* \.(js|css)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # ── Other static assets ───────────────────────────────────
    location ~* \.(png|jpg|jpeg|gif|ico|svg|woff2?|ttf|eot)$ {
        expires 30d;
        add_header Cache-Control "public";
    }

    # ── Gzip compression ──────────────────────────────────────
    gzip on;
    gzip_vary on;
    gzip_proxied any;
    gzip_comp_level 6;
    gzip_types
        text/plain
        text/css
        text/javascript
        application/javascript
        application/json
        application/x-javascript
        image/svg+xml;
    gzip_min_length 1024;
}
EOF

log "Uploading nginx config..."
scp -i "$EC2_KEY" -o StrictHostKeyChecking=no "$NGINX_CONF_LOCAL" "$EC2_USER@$EC2_HOST:/tmp/sevis-web-nginx.conf"
rm -f "$NGINX_CONF_LOCAL"

log "Installing config and restarting nginx..."
$SSH_CMD bash << NGINXSH
set -e

# Install nginx if somehow missing
if ! command -v nginx &>/dev/null; then
    echo "Installing nginx..."
    sudo dnf install -y nginx -q
fi

# Install config
sudo mv /tmp/sevis-web-nginx.conf /etc/nginx/conf.d/sevis-web.conf

# Remove the default nginx welcome page if it's there (conflicts with our server on port 80)
sudo rm -f /etc/nginx/conf.d/default.conf

# Test config
echo "nginx config test:"
sudo nginx -t 2>&1

# Enable + restart
sudo systemctl enable nginx --quiet
sudo systemctl restart nginx

sleep 2
if systemctl is-active nginx > /dev/null 2>&1; then
    echo "  nginx is active"
else
    echo "  ERROR: nginx failed to start"
    sudo journalctl -u nginx --no-pager -n 20
    exit 1
fi
NGINXSH
ok "nginx configured and running on port $WEB_PORT"

# ══════════════════════════════════════════════════════════════
# 5. Final status
# ══════════════════════════════════════════════════════════════
header "════════════════════════════════════════"
header " Final Server Status"
header "════════════════════════════════════════"

$SSH_CMD bash << 'STATUSSH'
BOLD='\033[1m'; GREEN='\033[0;32m'; RED='\033[0;31m'; YELLOW='\033[1;33m'; RESET='\033[0m'
BASE=~/sevis

echo ""
echo -e "${BOLD}Java Microservices:${RESET}"
ALL_OK=true
for SVC in eureka-server gateway user-service billing-service inventory-service orders-service; do
  PID_FILE=$BASE/$SVC.pid
  if [ -f "$PID_FILE" ]; then
    PID=$(cat "$PID_FILE")
    if kill -0 "$PID" 2>/dev/null; then
      echo -e "  ${GREEN}✓${RESET} $SVC  (PID $PID)"
    else
      echo -e "  ${RED}✗${RESET} $SVC  (PID $PID — NOT running)"
      ALL_OK=false
    fi
  else
    echo -e "  ${RED}✗${RESET} $SVC  (not started)"
    ALL_OK=false
  fi
done

echo ""
echo -e "${BOLD}Web Frontend:${RESET}"
if systemctl is-active nginx > /dev/null 2>&1; then
    echo -e "  ${GREEN}✓${RESET} nginx  (active)"
else
    echo -e "  ${RED}✗${RESET} nginx  (inactive)"
fi

echo ""
echo -e "${BOLD}Listening ports:${RESET}"
sudo ss -tlnp 2>/dev/null | awk 'NR>1{print "  " $4}' | sort -t: -k2 -n

echo ""
echo -e "${BOLD}Eureka registered services:${RESET}"
curl -s http://localhost:8761/eureka/apps 2>/dev/null \
    | grep -o '<app><name>[^<]*' \
    | sed 's/<app><name>/  ✓ /' \
    || echo "  (Eureka not reachable)"

echo ""
echo -e "${BOLD}Memory:${RESET}"
free -h | grep Mem | awk '{printf "  Total: %s  Used: %s  Available: %s\n", $2,$3,$7}'
STATUSSH

echo ""
echo -e "${BOLD}${GREEN}════════════════════════════════════════${RESET}"
echo -e "${BOLD}${GREEN} Deployment complete!${RESET}"
echo -e "${BOLD}${GREEN}════════════════════════════════════════${RESET}"
echo ""
echo -e "  Web app  : ${CYAN}http://$EC2_HOST${RESET}"
echo -e "  API      : ${CYAN}http://$EC2_HOST:8080${RESET}"
echo -e "  Eureka   : ${CYAN}http://$EC2_HOST:8761${RESET}"
echo ""
echo -e "${YELLOW}  NOTE: Ensure port $WEB_PORT is open in your EC2 security group.${RESET}"
echo ""
